webdriver.base.url=https://www.demoblaze.com/
serenity.browser.maximized=true
serenity.project.name=Demoblaze Automation Project
serenity.take.screenshots=FOR_EACH_ACTION
serenity.logging=VERBOSE
serenity.report.encoding=UTF-8
serenity.full.page.screenshot=true
serenity.report.show.releases=true
serenity.report.show.history=true
serenity.report.show.tag.filter=true
serenity.reports=single-page-html